name: Daily Realtime-DB Backup

on:
  schedule:
    - cron: '0 18 * * *'    # 2 AM Manila / 18:00 UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Dump RTDB to JSON
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
          PROJECT:      ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          mkdir -p backups
          firebase database:get / \
            --project "$PROJECT" \
            --token "$FIREBASE_TOKEN" \
            > backups/"$DATE".json

      - name: Commit & Push backup
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/"$DATE".json
          git commit -m "Backup $DATE" || echo "No changes to commit"
          git push
