name: Daily Firebase Backups

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # 2 AM Manila / 18:00 UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci               # or `npm install` if you don't have a lockfile

      - name: Dump RTDB & commit
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
          PROJECT:        ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          mkdir -p backups/rtdb
          firebase database:get / \
            --project "$PROJECT" \
            --token "$FIREBASE_TOKEN" \
            > backups/rtdb/"$DATE".json

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/rtdb/"$DATE".json
          git commit -m "RTDB backup $DATE" || echo "No RTDB changes"

      - name: Dump Firestore & commit
        env:
          FIRESTORE_SA_KEY: ${{ secrets.FIRESTORE_SA_KEY }}
        run: |
          node scripts/backup-firestore.js

          DATE=$(date -u +'%Y-%m-%d')
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/firestore/"$DATE"
          git commit -m "Firestore backup $DATE" || echo "No Firestore changes"

      - name: Push all backups
        run: git push origin HEAD:main
