name: Daily RTDB Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Dump RTDB & Commit backup
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
          PROJECT:        ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          mkdir -p backups
          firebase database:get / \
            --project "$PROJECT" \
            --token "$FIREBASE_TOKEN" \
            > backups/"$DATE".json

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/"$DATE".json
          git commit -m "Backup $DATE" || echo "No changes to commit"
          git push origin HEAD:main
